### ISSUE TITLE
R code in paper should be edited so it can be copied and pasted as is

### ISSUE THREAD

**Issue by joethorley** [flyaflya/causact#45]
for example

```
R> graph = dag_create() %>%
+    dag_node("Treatment Effect","y",
```

should be 

```
graph = dag_create() %>%
   dag_node("Treatment Effect","y",
```

etc

links to https://github.com/openjournals/joss-reviews/issues/4415

**Comment by flyaflya** [comment]
fixed.  https://github.com/flyaflya/causact/commit/c2497fae92caac6ce5bfbee42f06b3e81e59b468
