### ISSUE TITLE
I think the paper should acknowledge Doodlebugs in its comparison to other packages

### ISSUE THREAD

**Issue by joethorley** [flyaflya/causact#46]
I think this is relevant even if Doodlebugs is no longer supported in anyway

https://github.com/openjournals/joss-reviews/issues/4415

**Comment by joethorley** [comment]
I also think some discussion of dagitty is relevant http://dagitty.net

**Comment by flyaflya** [comment]
yes, these are good references.  Add here:  https://github.com/flyaflya/causact/commit/52bdbdcb7a0bec3b3f17afe6569855f1dbead8dd
