### ISSUE TITLE
`?causact` should bring up description of file

### ISSUE THREAD

**Issue by joethorley** [flyaflya/causact#51]
To generate run `usethis::use_package_doc()`

https://github.com/openjournals/joss-reviews/issues/4415

**Comment by flyaflya** [comment]
This is a great tip.  Very easy to fix.  Thx for the suggestion.

**Comment by flyaflya** [comment]
fixed here: https://github.com/flyaflya/causact/commit/a88e47f07833a1ea1dc5201e268d213b66746105
