### ISSUE TITLE
Converting Beta to Laplace?

### ISSUE THREAD

**Issue by prabinov42** [flyaflya/causact#57]
Running
`library(tidyverse)
library(causact)

set.seed(2023)
n_subjects <- 20

df <- tibble(id=1:(n_subjects)) %>%
  mutate(
    cond = sample(c('ctrl','trtmt'),nrow(.), replace=TRUE) ,
    trials = sample(5:25, nrow(.), replace=TRUE),
    lin_pred = -1+if_else(cond=='trtmt',1,0),
    prob = 1 / (1+exp(-lin_pred)),
    successes = rbinom(nrow(.),trials, prob)
  )

graph <- dag_create() %>%
  dag_node("Successes","s", rhs = binomial(trials,prob), data = dfo$successes) %>%
  dag_node("Probability","prob", child = "s", rhs =  beta(a,b)) %>%
  dag_node("a","a", child = "prob", rhs =  exponential(1)) %>%
  dag_node("b","b", child = "prob", rhs =  exponential(1)) %>%  
  dag_node("Trials","trials", child = "s", data = dfo$trials) %>%
  dag_plate("Cond","cond", nodeLabels = c("a","b"), data = dfo$cond, addDataNode = TRUE) %>%  
  dag_plate("Observation","i", nodeLabels = c("s","trials","prob","cond"))
graph %>% dag_render()
drawsDF <- graph %>% dag_numpyro()
`
gives an error:
Error in py_run_string_impl(code, local, convert) : 
  ValueError: BinomialProbs distribution got invalid probs parameter.
  
When I look at the generated numpyro code it is substituting 'Laplace' for Beta. When I change it back to Beta, the numpyro code seem to run ok.  

causact_0.5.2

**Comment by prabinov42** [comment]
Guessing it is this:
beta <- function(shape1, shape2, dim = NULL) {
  a_quo <- rlang::enquo(shape1)
  a_name <- rlang::quo_name(a_quo)
  b_quo <- rlang::enquo(shape2)
  b_name <- rlang::quo_name(b_quo)
  paste0("dist.Laplace(",a_name,",",b_name,")")
}

**Comment by flyaflya** [comment]
thanks Peter.  That is certainly a bug.  I am fixing it now.  Should have the fix up on CRAN shortly.

**Comment by flyaflya** [comment]
coming to CRAN shortly.  FIxed this bug in commit https://github.com/flyaflya/causact/commit/98f1c2e73cfd823532e8b9e5d643c497537af105
